# Generated by Django 5.2.3 on 2025-06-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва Дилерства')),
                ('city', models.CharField(default='Київ', max_length=100)),
                ('address', models.CharField(help_text='Повна адреса дилерства', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeslaCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('M3', 'Model 3'), ('MY', 'Model Y'), ('MS', 'Model S'), ('MX', 'Model X'), ('CYT', 'Cybertruck')], max_length=3, verbose_name='Модель Tesla')),
                ('year', models.IntegerField(default=2025, help_text='Рік випуску автомобіля')),
                ('color', models.CharField(choices=[('BLK', 'Чорний'), ('WHT', 'Білий'), ('RED', 'Червоний'), ('BLU', 'Синій'), ('GRY', 'Сірий')], default='WHT', max_length=3, verbose_name='Колір')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ціна автомобіля в USD', max_digits=10)),
                ('mileage', models.IntegerField(default=0, help_text='Пробіг автомобіля в кілометрах', verbose_name='Пробіг (км)')),
                ('drivetrain', models.CharField(choices=[('RWD', 'Задній привід (RWD)'), ('AWD', 'Повний привід (AWD)')], default='AWD', max_length=3, verbose_name='Тип приводу')),
                ('battery_range_km', models.IntegerField(blank=True, help_text='Заявлений запас ходу на повному заряді', null=True, verbose_name='Запас ходу (км)')),
                ('vin', models.CharField(help_text='Унікальний ідентифікаційний номер транспортного засобу (VIN)', max_length=17, unique=True, verbose_name='VIN номер')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новий автомобіль')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.dealership', verbose_name='Дилерство')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
